### ISSUE TITLE
Swagger uses `{param}` path params instead of `:param`

### ISSUE THREAD

**Issue by rricard** [rricard/koa-swagger#2]

**Comment by philip1986** [comment]
+1 
There is a [fork](https://github.com/theomega/koa-swagger) from @theomega, which includes a solution for this issue. I would like to see this merged into this repo and released on npm. I opened a PR for this purpose, please have a look.

**Comment by rricard** [comment]
@philip1986 I'll take a look, sorry the project is not actively maintained but I'm happy to merge some stuff. If you are interested in taking the project, I can add you has a contributor (write access) as well at some point.

**Comment by rricard** [comment]
Fixed by #5

**Comment by philip1986** [comment]
@rricard thx for the quick reaction. I would be glad to become a collaborator of this project.
